### ISSUE TITLE
Sha256sum not working on MacOS

### ISSUE THREAD

**Issue by MunchDev** [sio/Makefile.venv#11]
I'm using Big Sur 11.2.

Somehow, `sha256sum` is not pre-installed on my machine. So I have to change from:
```
echo "5afbcf51a82f629cd65ff23185acde90ebe4dec889ef80bbdc12562fbd0b2611 *Makefile.fetched" \
		| sha256sum --check - \
		&& mv Makefile.fetched Makefile.venv
```
to:
```
echo "5afbcf51a82f629cd65ff23185acde90ebe4dec889ef80bbdc12562fbd0b2611 *Makefile.fetched" \
		| shasum -a 256 --check - \
		&& mv Makefile.fetched Makefile.venv
```

Wonder if it should be updated...

**Comment by sio** [comment]
Yeah... macOS does not ship GNU coreutils by default, you need to install them via brew or in some other way. That makes me wonder, which make implementation is shipped by default (if any)? Could you paste the output of `make --version`?

I am hesitant to change installation instructions as you suggested, because calling Perl to calculate a hash sum instead of using coreutils feels deeply wrong to me. I think I'll add a note about coreutils and mention your workaround too.

**Comment by MunchDev** [comment]
Output for `make --version`:
```
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
```

**Comment by sio** [comment]
Oh, it's not bad and it's not about coreutils per se. It just feels wrong to me to call into interpreted language for a number-crunching task when there exists a compiled binary tool for the same purpose.

**Comment by MunchDev** [comment]
Personally, I don't think the performance loss is really significant, since the file `Makefile.venv` isn't really big. Yet, if `shasum` is shipped with all Linux distributions plus MacOS, so why not use it?

Apologise if I ask a stupid question!

**Comment by sio** [comment]
Your question is not stupid :) I'm being somewhat irrational here, you're right about performance being similar for small files. I'm being too much of a GNU fanboy :)

I'll look into how ubiquitous Perl currently is. I'll check if common Docker containers ship with Perl included, since it's the only scenario I could think of that's questionable. Then will take a 1-2 day pause to let this sink in, but yeah, the rational thing would be to agree with you.

**Comment by sio** [comment]
My intuition proved correct. `shasum` is not included into any of base Docker images (Alpine, Debian, Ubuntu, Centos). Even though `shasum` is part of Perl package, deb-based distros provide a smaller `perl-base` (without `shasum`) which is enough for OS tools to function.

On the other hand, GNU coreutils are present in each of those images.

I'll add a note about macOS to README now, but the instructions should stay unchanged.
