### ISSUE TITLE
pyproject.toml

### ISSUE THREAD

**Issue by sla-te** [sio/Makefile.venv#22]
hi, thanks for the nice timesaving package - would you happen to know how I can integrate usage of pyproject.toml over requirements.txt?

**Comment by sio** [comment]
Thanks for reaching out! I'm glad you find Makefile.venv useful.

As you have correctly noted, `pyproject.toml` is treated in the same way as `setup.py` (in regards to maintaining Python virtual environment). In fact, you can set `SETUP_PY=pyproject.toml` and use Makefile.venv without any modifications, like I do [here](https://github.com/sio/pelican-smallweb/blob/a52f646437a009929189f40bfb25e9938b65b5ae/Makefile).

I know, such counterintuitive naming is not great. On the other hand, adding repetitive code that does the same thing for a slightly different input is also not great. Since `pyproject.toml` is [neither a new nor a fringe thing](https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/) for quite a long time I agree that it's rational for our users to expect it to work out of the box. I'll think about more elegant way to add it to Makefile.venv in the following week(s).

---

PS: Changes to source code are a lot easier to comprehend when they are submitted in a [diff format](https://en.wikipedia.org/wiki/Diff):

```diff
--- Makefile.venv	2023-04-10 10:12:28.777824500 +0300
+++ Makefile.venv@sla-te	2023-04-10 10:12:50.583479700 +0300
@@ -88,6 +88,7 @@
 REQUIREMENTS_TXT?=$(wildcard requirements.txt)  # Multiple paths are supported (space separated)
 SETUP_PY?=$(wildcard setup.py)                  # Multiple paths are supported (space separated)
 SETUP_CFG?=$(foreach s,$(SETUP_PY),$(wildcard $(patsubst %setup.py,%setup.cfg,$(s))))
+PYPROJECT_TOML?=$(wildcard pyproject.toml)
 MARKER=.initialized-with-Makefile.venv
 
 
@@ -204,6 +205,7 @@
 	$(info REQUIREMENTS_TXT="$(REQUIREMENTS_TXT)")
 	$(info SETUP_PY="$(SETUP_PY)")
 	$(info SETUP_CFG="$(SETUP_CFG)")
+	$(info PYPROJECT_TOML="$(PYPROJECT_TOML)")
 	$(info VENVDIR="$(VENVDIR)")
 	$(info VENVDEPENDS="$(VENVDEPENDS)")
 	$(info WORKDIR="$(WORKDIR)")
@@ -223,6 +225,9 @@
 ifneq ($(strip $(SETUP_CFG)),)
 VENVDEPENDS+=$(SETUP_CFG)
 endif
+ifneq ($(strip $(PYPROJECT_TOML)),)
+VENVDEPENDS+=$(PYPROJECT_TOML)
+endif
 
 $(VENV):
 	$(PY) -m venv $(VENVDIR)
@@ -235,6 +240,9 @@
 ifneq ($(strip $(SETUP_PY)),)
 	$(VENV)/pip install $(foreach path,$(SETUP_PY),-e $(dir $(path)))
 endif
+ifneq ($(strip $(PYPROJECT_TOML)),)
+	$(VENV)/pip install $(foreach path,$(PYPROJECT_TOML),-e $(dir $(path)))
+endif
 	$(call touch,$(VENV)/$(MARKER))
```

PPS: There is also the whole [pull request process](https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/) for submitting changes to open source projects at GitHub.

PPPS: Please do not consider my post-scriptums to be scolding or condescending. You did a good thing by reaching out and pointing out a way to improve this project. I feel grateful for this and the fact that you did it in slightly suboptimal way does not detract from that feeling. I see that you're new to this and I wrote these PS'es to provide you some pointers to new knowledge.

**Comment by sio** [comment]
Done: https://github.com/sio/Makefile.venv/commit/da7149cb5582cc2752e15217e872b08eb0d7894e 😄

Thank you for the suggestion!
