### ISSUE TITLE
Source .env for interactive shell targets

### ISSUE THREAD

**Issue by jdkelleher** [sio/Makefile.venv#23]
First, let me say I love this project. I started down this road myself a few hours before finding it. Super helpful, saved me a lot of time, and showed me things I hadn't even thought of yet.

I'm using GitHub actions which are dependent on environment variables that should not be stored in git. A local .env file which ii sourced by targets while testing supports this workflow.

Enabling the shell targets to source a .env file would remove a step if doing more interactive manual testing.

**Comment by sio** [comment]
Thanks for reaching out! I'm glad that you find this project useful.

I'm grateful for the suggestion but I see multiple drawbacks and hard-to-handle edge cases, so I'm inclined to say no to this. 

Here are my concerns:

- I see no way to automate sourcing .env in non-interactive targets (like [`test` recipe in README](https://github.com/sio/Makefile.venv#samples)).
- Adding .env functionality only to interactive targets (like you do in [#24](https://github.com/sio/Makefile.venv/pull/24)) violates the principle of least surprise. In my experience these targets are rarely used outside of debug/development cycle - making them behave differently to most of Makefile.venv invocations would certainly lead to some woah moments and hard-to-debug failures.
- It's hard to decide on where we should expect .env to be located. Is it `$(CURDIR)` or `$(WORKDIR)`? Or maybe the directory with the makefile? Which of those: top-level one or Makefile.venv? Do we hardcode one of those or do we implement some walking-up-the-tree logic like git does? What if user prefers to name their .env files differently? Do we add a new variable just for the file name (while keeping the directory finding logic) or for the full path?
- After sorting out the issues listed above the PR implementing this feature would also have to include some tests (which your PR currently lacks).

Instead of adding this feature to Makefile.venv I would suggest you to put `-include .env` into your main Makefile. GNU Make variable declarations are similar to but not exactly the same as the ones in POSIX shell, so you'd need to be careful to use only the common syntax subset, but for simple key-value pairs it seems doable. Hyphen in front of `-include` will suppress the error in case .env file is missing.

**Comment by jdkelleher** [comment]
All very good points and I agree with your assessment that `-include .env` is a cleaner option. That means values can't be quoted, but it is not a terrible burden for this use case. Thanks again.
